export interface CatalogCheck {
  id: string;
  layer: 'Production' | 'UX' | 'UI' | 'States' | 'Polish';
  tier: 'A' | 'B' | 'C' | 'D';
  title: string;
  description: string;
}

export const AUDIT_CATALOG_200: CatalogCheck[] = [
  // --- PRODUCTION (40 Checks) ---
  { id: 'PROD-01', layer: 'Production', tier: 'A', title: 'HTTPS & SSL/TLS Protocol Enforcement', description: 'Enforces HTTPS encryption and prevents unencrypted plaintext HTTP transport.' },
  { id: 'PROD-02', layer: 'Production', tier: 'A', title: 'Strict-Transport-Security (HSTS)', description: 'Validates HSTS header with max-age >= 31536000 and includeSubDomains.' },
  { id: 'PROD-03', layer: 'Production', tier: 'A', title: 'Content Security Policy (CSP)', description: 'Verifies Content-Security-Policy header prevents XSS and malicious script injections.' },
  { id: 'PROD-04', layer: 'Production', tier: 'A', title: 'X-Frame-Options Clickjacking Defense', description: 'Prevents iframe framing attacks via DENY or SAMEORIGIN.' },
  { id: 'PROD-05', layer: 'Production', tier: 'A', title: 'X-Content-Type-Options No-Sniff', description: 'Prevents MIME-type sniffing vulnerabilities via nosniff header.' },
  { id: 'PROD-06', layer: 'Production', tier: 'A', title: 'DNS Pre-resolution & Prefetch Integrity', description: 'Ensures external origins have dns-prefetch and preconnect resource hints.' },
  { id: 'PROD-07', layer: 'Production', tier: 'A', title: 'HTTP/2 & HTTP/3 Transport Protocol', description: 'Validates modern multiplexed HTTP connection over legacy HTTP/1.1.' },
  { id: 'PROD-08', layer: 'Production', tier: 'A', title: 'Gzip & Brotli Content Encoding', description: 'Verifies asset responses use modern compression (br or gzip).' },
  { id: 'PROD-09', layer: 'Production', tier: 'A', title: 'Console Error & Warning Hygiene', description: 'Monitors runtime CDP console for unhandled syntax or network exceptions.' },
  { id: 'PROD-10', layer: 'Production', tier: 'A', title: 'Unhandled Promise Rejection Guard', description: 'Catches unhandled async exceptions escaping global error boundaries.' },
  { id: 'PROD-11', layer: 'Production', tier: 'A', title: 'Localhost & Dev URL Leakage Detection', description: 'Detects hardcoded dev ports (localhost:3000, 127.0.0.1) in production markup.' },
  { id: 'PROD-12', layer: 'Production', tier: 'A', title: 'Literal "undefined" DOM Render Guard', description: 'Flags unhandled JavaScript nullish values leaking as literal string in DOM.' },
  { id: 'PROD-13', layer: 'Production', tier: 'A', title: 'Literal "[object Object]" DOM Leak Guard', description: 'Flags unhandled object string conversions rendered to end users.' },
  { id: 'PROD-14', layer: 'Production', tier: 'A', title: 'Dead Navigation Links (404/500)', description: 'Crawls internal same-origin anchors to guarantee zero broken routes.' },
  { id: 'PROD-15', layer: 'Production', tier: 'A', title: 'Production Sourcemap Cloaking', description: 'Ensures proprietary application source code is not exposed in public bundles.' },
  { id: 'PROD-16', layer: 'Production', tier: 'A', title: 'Subresource Integrity (SRI)', description: 'Verifies third-party CDN scripts specify integrity SHA hashes.' },
  { id: 'PROD-17', layer: 'Production', tier: 'A', title: 'Static Asset Cache-Control Policy', description: 'Validates immutable caching headers (max-age=31536000) for hashed bundles.' },
  { id: 'PROD-18', layer: 'Production', tier: 'A', title: 'Robots.txt Crawl Permissions', description: 'Ensures robots.txt is well-formed without blocking critical CSS/JS assets.' },
  { id: 'PROD-19', layer: 'Production', tier: 'A', title: 'Sitemap.xml Schema Validation', description: 'Verifies XML sitemap exists and links to valid canonical routes.' },
  { id: 'PROD-20', layer: 'Production', tier: 'A', title: 'Standard Favicon Availability', description: 'Ensures favicon.ico exists and serves valid image MIME type.' },
  { id: 'PROD-21', layer: 'Production', tier: 'A', title: 'Apple Touch Icon Specification', description: 'Validates high-resolution apple-touch-icon link for mobile home screens.' },
  { id: 'PROD-22', layer: 'Production', tier: 'A', title: 'OpenGraph Protocol Meta Tags', description: 'Validates og:title, og:description, og:image, and og:url tags for social sharing.' },
  { id: 'PROD-23', layer: 'Production', tier: 'A', title: 'Twitter Card Metadata Integration', description: 'Verifies twitter:card and twitter:title for rich preview cards.' },
  { id: 'PROD-24', layer: 'Production', tier: 'A', title: 'Canonical Link Tag Uniqueness', description: 'Ensures rel="canonical" link matches the normalized canonical URL.' },
  { id: 'PROD-25', layer: 'Production', tier: 'A', title: 'Cookie Secure Flag Enforcement', description: 'Guarantees authentication and session cookies mandate Secure flag.' },
  { id: 'PROD-26', layer: 'Production', tier: 'A', title: 'Cookie HttpOnly Protection', description: 'Ensures sensitive session tokens are inaccessible via client JavaScript.' },
  { id: 'PROD-27', layer: 'Production', tier: 'A', title: 'Cookie SameSite CSRF Defense', description: 'Verifies cookies use SameSite=Lax or SameSite=Strict.' },
  { id: 'PROD-28', layer: 'Production', tier: 'A', title: 'CORS Access-Control-Allow-Origin', description: 'Guarantees APIs restrict CORS headers to trusted origins.' },
  { id: 'PROD-29', layer: 'Production', tier: 'A', title: 'Time to First Byte (TTFB) Latency', description: 'Evaluates server response time remains under 600ms on edge locations.' },
  { id: 'PROD-30', layer: 'Production', tier: 'A', title: 'Server Identification Header Masking', description: 'Prevents exposing detailed backend server version strings in headers.' },
  { id: 'PROD-31', layer: 'Production', tier: 'A', title: 'Mixed Content Block & Guard', description: 'Ensures zero HTTP resources are fetched within an HTTPS document.' },
  { id: 'PROD-32', layer: 'Production', tier: 'A', title: 'DOM Tree Nesting Depth Threshold', description: 'Flags excessive DOM nesting exceeding 32 levels to protect parser budget.' },
  { id: 'PROD-33', layer: 'Production', tier: 'A', title: 'Total DOM Node Count Guard (<1500)', description: 'Prevents bloated initial DOM trees from exhausting mobile memory.' },
  { id: 'PROD-34', layer: 'Production', tier: 'A', title: 'Unused CSS Bundle Tree-Shaking', description: 'Detects oversized CSS bundles with >60% unreferenced classes.' },
  { id: 'PROD-35', layer: 'Production', tier: 'A', title: 'Script Async & Defer Non-blocking', description: 'Guarantees non-critical head scripts avoid render-blocking execution.' },
  { id: 'PROD-36', layer: 'Production', tier: 'A', title: 'Critical Hero Image Preload Hint', description: 'Verifies primary above-the-fold image uses rel="preload" as="image".' },
  { id: 'PROD-37', layer: 'Production', tier: 'A', title: 'Vercel / Edge Network Header Health', description: 'Verifies edge cache status (HIT/STALE) and serverless execution latency.' },
  { id: 'PROD-38', layer: 'Production', tier: 'A', title: 'API Client Timeout Circuit Breaker', description: 'Ensures frontend fetch calls implement abort signals or timeout guards.' },
  { id: 'PROD-39', layer: 'Production', tier: 'A', title: 'JSON-LD Structured Data Syntax', description: 'Validates schema.org JSON-LD snippets parse without syntax errors.' },
  { id: 'PROD-40', layer: 'Production', tier: 'A', title: 'Graceful Error Boundary Recovery', description: 'Ensures React/Next error boundaries provide user-friendly retry buttons.' },

  // --- UX & USABILITY (40 Checks) ---
  { id: 'UX-01', layer: 'UX', tier: 'A', title: 'Mobile Tap Target Sizing (>=44x44px)', description: 'Enforces WCAG 2.5.5 minimum touch dimensions on mobile viewports.' },
  { id: 'UX-02', layer: 'UX', tier: 'A', title: 'Touch Target Inter-Element Spacing', description: 'Guarantees minimum 8px margin separation between adjacent interactive targets.' },
  { id: 'UX-03', layer: 'UX', tier: 'A', title: 'Input Form Autocomplete Attributes', description: 'Validates autocomplete tags on email, name, address, and password fields.' },
  { id: 'UX-04', layer: 'UX', tier: 'A', title: 'Semantic Input Type Correctness', description: 'Ensures numeric/email inputs use type="email" and inputmode="numeric".' },
  { id: 'UX-05', layer: 'UX', tier: 'A', title: 'Persistent Form Field Labels', description: 'Flags forms relying solely on placeholder text without associated <label>.' },
  { id: 'UX-06', layer: 'UX', tier: 'A', title: 'Form Inline Error Accessibility (ARIA)', description: 'Verifies invalid input fields link to error text via aria-describedby.' },
  { id: 'UX-07', layer: 'UX', tier: 'A', title: 'Logical Keyboard Tab Order Progression', description: 'Guarantees tabIndex follows DOM reading order without negative values.' },
  { id: 'UX-08', layer: 'UX', tier: 'A', title: 'Keyboard Focus-Visible Ring Indicator', description: 'Ensures all focusable elements present high-contrast focus rings.' },
  { id: 'UX-09', layer: 'UX', tier: 'A', title: 'Modal Dialog Keyboard Focus Trapping', description: 'Traps keyboard tab navigation inside open dialogs to prevent background bleed.' },
  { id: 'UX-10', layer: 'UX', tier: 'A', title: 'Modal Dismissal via ESC Key Handler', description: 'Guarantees user can close any open modal by pressing the Escape key.' },
  { id: 'UX-11', layer: 'UX', tier: 'A', title: 'Modal Backdrop Click Outside Dismiss', description: 'Enables dismissing overlays by clicking the dim background backdrop.' },
  { id: 'UX-12', layer: 'UX', tier: 'A', title: 'Mobile Viewport Zoomability (No user-scalable=no)', description: 'Prevents disabling pinch-to-zoom to maintain accessibility for low-vision users.' },
  { id: 'UX-13', layer: 'UX', tier: 'A', title: 'Page Scale Factor Resilience (200% Zoom)', description: 'Verifies page layout does not break when browser zoom is set to 200%.' },
  { id: 'UX-14', layer: 'UX', tier: 'A', title: 'Skip to Main Content Anchor Link', description: 'Provides accessible keyboard shortcut link directly to the <main> landmark.' },
  { id: 'UX-15', layer: 'UX', tier: 'A', title: 'Semantic HTML5 Landmark Structure', description: 'Validates proper header, nav, main, section, and footer landmarks.' },
  { id: 'UX-16', layer: 'UX', tier: 'A', title: 'Screen Reader ARIA Live Status Updates', description: 'Announces dynamic toast notifications and progress meters via aria-live.' },
  { id: 'UX-17', layer: 'UX', tier: 'A', title: 'Hyperlink Text Context & Clarity', description: 'Flags ambiguous link text such as "click here" or "read more".' },
  { id: 'UX-18', layer: 'UX', tier: 'A', title: 'Destructive Action Confirmation Prompt', description: 'Ensures permanent delete/purge operations require affirmative confirmation.' },
  { id: 'UX-19', layer: 'UX', tier: 'A', title: 'Browser Back Button History Integrity', description: 'Guarantees SPA navigation updates browser history without trapping users.' },
  { id: 'UX-20', layer: 'UX', tier: 'A', title: 'Unsaved Form Changes Warning Dialog', description: 'Alerts users before navigating away from partially filled forms.' },
  { id: 'UX-21', layer: 'UX', tier: 'A', title: 'Search Input Instant Clear Action', description: 'Provides 1-tap clear button inside active search and filter fields.' },
  { id: 'UX-22', layer: 'UX', tier: 'A', title: 'Empty Search Query Graceful Handling', description: 'Prevents page crashes or blank views when submitting empty search terms.' },
  { id: 'UX-23', layer: 'UX', tier: 'A', title: 'Search Results Count Announcement', description: 'Clearly states number of matching items found for screen readers.' },
  { id: 'UX-24', layer: 'UX', tier: 'A', title: 'Infinite Scroll Footer Reachability', description: 'Guarantees essential footer links remain reachable on infinite lists.' },
  { id: 'UX-25', layer: 'UX', tier: 'A', title: 'Pagination Boundary Controls', description: 'Disables "Previous" on page 1 and "Next" on terminal page.' },
  { id: 'UX-26', layer: 'UX', tier: 'A', title: 'Breadcrumb Navigation Hierarchy', description: 'Provides structured breadcrumb trail for deep subpage navigation.' },
  { id: 'UX-27', layer: 'UX', tier: 'A', title: 'External Links Rel="noopener noreferrer"', description: 'Protects target="_blank" links against tabnabbing vulnerabilities.' },
  { id: 'UX-28', layer: 'UX', tier: 'A', title: 'Interactive Element ARIA Roles', description: 'Ensures div/span click triggers declare role="button" and tabIndex={0}.' },
  { id: 'UX-29', layer: 'UX', tier: 'A', title: 'Accessible Name Computation Coverage', description: 'Guarantees all buttons, links, and inputs have accessible computed names.' },
  { id: 'UX-30', layer: 'UX', tier: 'A', title: 'Icon-Only Button Tooltip & Labels', description: 'Validates aria-label or title on SVG icon action buttons.' },
  { id: 'UX-31', layer: 'UX', tier: 'A', title: 'Disabled Control Visual & ARIA Semantics', description: 'Pairs aria-disabled="true" with clear visual styling and tooltip explanation.' },
  { id: 'UX-32', layer: 'UX', tier: 'A', title: 'Tooltip Hover Intent Delay (150ms)', description: 'Prevents flickering tooltips by applying subtle 150ms hover delay.' },
  { id: 'UX-33', layer: 'UX', tier: 'A', title: 'Tooltip Keyboard Focus Accessibility', description: 'Ensures tooltips open on keyboard focus in addition to pointer hover.' },
  { id: 'UX-34', layer: 'UX', tier: 'A', title: 'Password Field Show/Hide Toggle', description: 'Offers toggle button to reveal password text on mobile keyboards.' },
  { id: 'UX-35', layer: 'UX', tier: 'A', title: 'Password Paste Permission Guard', description: 'Guarantees password managers can paste credentials into password fields.' },
  { id: 'UX-36', layer: 'UX', tier: 'A', title: 'CAPTCHA Accessible Fallback Option', description: 'Provides audio or alternative verification challenge for vision impaired.' },
  { id: 'UX-37', layer: 'UX', tier: 'A', title: 'Horizontal Scrollbar Lockout on Mobile', description: 'Eliminates accidental horizontal swipe-out on 390px phone screens.' },
  { id: 'UX-38', layer: 'UX', tier: 'A', title: 'Device Orientation Switch Resilience', description: 'Smoothly adapts layout between portrait and landscape modes.' },
  { id: 'UX-39', layer: 'UX', tier: 'A', title: 'Copy-to-Clipboard Instant Toast Alert', description: 'Confirms clipboard copy actions with clear visual toast feedback.' },
  { id: 'UX-40', layer: 'UX', tier: 'A', title: 'Content Readability & Typography Scale', description: 'Evaluates reading clarity, sentence structure, and scanning ergonomics.' },

  // --- UI & LAYOUT (40 Checks) ---
  { id: 'UI-01', layer: 'UI', tier: 'A', title: 'Body Text Contrast Ratio (>=4.5:1)', description: 'Enforces WCAG AA contrast ratio between body typography and background.' },
  { id: 'UI-02', layer: 'UI', tier: 'A', title: 'Large Heading Contrast Ratio (>=3.0:1)', description: 'Validates contrast ratio for typography >= 18pt or 14pt bold.' },
  { id: 'UI-03', layer: 'UI', tier: 'A', title: 'UI Component Border Contrast (>=3.0:1)', description: 'Ensures input boundaries and card borders are perceptible against canvas.' },
  { id: 'UI-04', layer: 'UI', tier: 'A', title: 'Text Contrast Against Gradient Backgrounds', description: 'Validates text legibility across all points of CSS gradient fills.' },
  { id: 'UI-05', layer: 'UI', tier: 'A', title: 'Optimal Reading Line Length (45-75 chars)', description: 'Prevents unbounded horizontal text lines that cause reader fatigue.' },
  { id: 'UI-06', layer: 'UI', tier: 'A', title: 'Strict Heading Hierarchy Progression', description: 'Enforces H1 -> H2 -> H3 logical progression without skipping levels.' },
  { id: 'UI-07', layer: 'UI', tier: 'A', title: 'Single Page H1 Heading Requirement', description: 'Guarantees each view contains exactly one primary H1 landmark.' },
  { id: 'UI-08', layer: 'UI', tier: 'A', title: 'Cumulative Layout Shift (CLS < 0.1)', description: 'Guarantees elements do not shift unexpectedly during render and load.' },
  { id: 'UI-09', layer: 'UI', tier: 'A', title: 'Font-Display: Swap Optimization', description: 'Eliminates invisible text flash (FOIT) by specifying font-display: swap.' },
  { id: 'UI-10', layer: 'UI', tier: 'A', title: 'Custom Web Font Preload Declaration', description: 'Preloads critical brand webfonts to eliminate late layout reflows.' },
  { id: 'UI-11', layer: 'UI', tier: 'A', title: 'Explicit Image Width & Height Dimensions', description: 'Prevents CLS by declaring width/height or aspect-ratio on all <img>.' },
  { id: 'UI-12', layer: 'UI', tier: 'A', title: 'Descriptive Image Alt Attribute Coverage', description: 'Guarantees all informative images have meaningful alt descriptions.' },
  { id: 'UI-13', layer: 'UI', tier: 'A', title: 'Image Lazy-Loading Attribute Support', description: 'Applies loading="lazy" to off-screen below-the-fold graphics.' },
  { id: 'UI-14', layer: 'UI', tier: 'A', title: 'Responsive Flexbox & Grid Wrapping', description: 'Ensures multi-card rows wrap cleanly without horizontal viewport clipping.' },
  { id: 'UI-15', layer: 'UI', tier: 'A', title: 'Text Truncation & Ellipsis Safety', description: 'Prevents overflowing strings from breaking container bounding boxes.' },
  { id: 'UI-16', layer: 'UI', tier: 'A', title: 'Container Overflow Hidden Clipping Guard', description: 'Flags unintended text clipping under overflow: hidden constraints.' },
  { id: 'UI-17', layer: 'UI', tier: 'A', title: 'Sticky Header Content Occlusion Guard', description: 'Ensures anchor scroll jumps pad for sticky navigation bars.' },
  { id: 'UI-18', layer: 'UI', tier: 'A', title: 'Z-Index Layer Collision Prevention', description: 'Prevents dropdown menus and tooltips from falling behind sticky panels.' },
  { id: 'UI-19', layer: 'UI', tier: 'A', title: 'Responsive Data Table Mobile Adaptation', description: 'Converts wide data tables to card stacks or scroll containers on mobile.' },
  { id: 'UI-20', layer: 'UI', tier: 'A', title: 'Multi-Column Grid Responsive Collapse', description: 'Collapses 3-4 column grids down to 1-2 columns on mobile screens.' },
  { id: 'UI-21', layer: 'UI', tier: 'A', title: 'Typography Scale Ratio Consistency', description: 'Verifies modular typographic scale adherence across title tiers.' },
  { id: 'UI-22', layer: 'UI', tier: 'A', title: 'Button Font-Weight & Case Harmony', description: 'Guarantees visual consistency across primary and secondary button labels.' },
  { id: 'UI-23', layer: 'UI', tier: 'A', title: '8pt Spacing Grid System Adherence', description: 'Checks that padding and margins align with an 8px or 4px design grid.' },
  { id: 'UI-24', layer: 'UI', tier: 'A', title: 'Border Radius Geometric Harmonization', description: 'Ensures nested containers radius values match outer frame curvature.' },
  { id: 'UI-25', layer: 'UI', tier: 'A', title: 'Form Input Active Border Highlight', description: 'Provides clear visual border tint on active focused input fields.' },
  { id: 'UI-26', layer: 'UI', tier: 'A', title: 'Subtle Drop Shadow Elevation Depth', description: 'Validates realistic multi-layered shadow offsets for depth hierarchy.' },
  { id: 'UI-27', layer: 'UI', tier: 'A', title: 'Dark Mode Theme Contrast Balance', description: 'Ensures dark theme avoids pure #000/#fff extremes for eye comfort.' },
  { id: 'UI-28', layer: 'UI', tier: 'A', title: 'Accent Color Vibrant Saturation Guard', description: 'Prevents neon primary accents that cause chromatic aberration.' },
  { id: 'UI-29', layer: 'UI', tier: 'A', title: 'Glassmorphism Backdrop Blur Fallback', description: 'Provides opaque background fallback for browsers lacking backdrop-filter.' },
  { id: 'UI-30', layer: 'UI', tier: 'A', title: 'High Contrast Mode (forced-colors) Support', description: 'Ensures borders and icons remain visible under Windows High Contrast mode.' },
  { id: 'UI-31', layer: 'UI', tier: 'A', title: 'SVG ViewBox Scale & Aspect Ratio', description: 'Guarantees vector icons scale sharply without pixelation or clipping.' },
  { id: 'UI-32', layer: 'UI', tier: 'A', title: 'Vector Graphic Crisp Rendering (-webkit-font-smoothing)', description: 'Enforces subpixel antialiasing on modern high-DPI displays.' },
  { id: 'UI-33', layer: 'UI', tier: 'A', title: 'System Emoji Font Stack Fallback', description: 'Includes Apple Color Emoji and Segoe UI Emoji in font declarations.' },
  { id: 'UI-34', layer: 'UI', tier: 'A', title: 'Body Line-Height Ratio (1.5x - 1.7x)', description: 'Maintains optimal proportional line spacing for body text readability.' },
  { id: 'UI-35', layer: 'UI', tier: 'A', title: 'Heading Letter-Spacing (Tracking) Tuning', description: 'Applies slight negative tracking to large display headings for punch.' },
  { id: 'UI-36', layer: 'UI', tier: 'A', title: 'Paragraph Bottom Margin Rhythm', description: 'Ensures paragraphs maintain consistent vertical paragraph margins.' },
  { id: 'UI-37', layer: 'UI', tier: 'A', title: 'Unordered List Bullet & Indent Alignment', description: 'Guarantees list bullets align neatly with text baseline.' },
  { id: 'UI-38', layer: 'UI', tier: 'A', title: 'Badge Pill Symmetric Padding Ratio', description: 'Verifies status badge pills maintain balanced horizontal/vertical padding.' },
  { id: 'UI-39', layer: 'UI', tier: 'A', title: 'Card Container Border Width Consistency', description: 'Enforces 1px or 2px uniform border thickness across grid cards.' },
  { id: 'UI-40', layer: 'UI', tier: 'A', title: 'Code Block Horizontal Scrollbar Containment', description: 'Prevents pre/code elements from blowing out page horizontal width.' },

  // --- STATES & RESILIENCE (40 Checks) ---
  { id: 'STATES-01', layer: 'States', tier: 'A', title: 'Button Async Loading Spinner State', description: 'Renders inline loading indicator upon initiating asynchronous actions.' },
  { id: 'STATES-02', layer: 'States', tier: 'A', title: 'Button Disabled Visual Dimming Treatment', description: 'Dims disabled buttons to opacity-50 with cursor-not-allowed.' },
  { id: 'STATES-03', layer: 'States', tier: 'A', title: 'Rapid Click Debounce & Duplicate Guard', description: 'Prevents accidental double submissions on rapid successive clicks.' },
  { id: 'STATES-04', layer: 'States', tier: 'A', title: 'Empty Content State Copy & Graphic', description: 'Renders encouraging illustration and action guide when lists are empty.' },
  { id: 'STATES-05', layer: 'States', tier: 'A', title: 'Zero Filter Results Recovery Suggestion', description: 'Provides "Clear All Filters" button when search produces no matches.' },
  { id: 'STATES-06', layer: 'States', tier: 'A', title: 'Network Offline Notification Banner', description: 'Displays persistent alert banner when navigator.onLine is false.' },
  { id: 'STATES-07', layer: 'States', tier: 'A', title: 'Network Reconnection Toast Feedback', description: 'Displays success toast confirming connection restoration.' },
  { id: 'STATES-08', layer: 'States', tier: 'A', title: 'High-Latency Network Slow Indicator', description: 'Informs user if backend response takes longer than 3 seconds.' },
  { id: 'STATES-09', layer: 'States', tier: 'A', title: 'Real-Time Form Field Error Feedback', description: 'Highlights invalid inputs immediately upon blur without full submit.' },
  { id: 'STATES-10', layer: 'States', tier: 'A', title: 'Form Submit Multi-Submit Disablement', description: 'Locks form submission button while network request is pending.' },
  { id: 'STATES-11', layer: 'States', tier: 'A', title: 'Server Error 500 Graceful Recovery', description: 'Offers retry button and status update during backend outage.' },
  { id: 'STATES-12', layer: 'States', tier: 'A', title: 'Client Error 400 Explanatory Notice', description: 'Explains validation reasons clearly rather than showing raw error codes.' },
  { id: 'STATES-13', layer: 'States', tier: 'A', title: 'Partial Content Failure Fallback', description: 'Renders remainder of page even if a single widget fails to load.' },
  { id: 'STATES-14', layer: 'States', tier: 'A', title: 'Broken Image Graphic Fallback', description: 'Renders placeholder icon when an image URL returns 404.' },
  { id: 'STATES-15', layer: 'States', tier: 'A', title: 'Video Playback Error Notice', description: 'Notifies user if embedded video stream fails to decode.' },
  { id: 'STATES-16', layer: 'States', tier: 'A', title: 'Audio Stream Interruption Handler', description: 'Allows restarting audio if browser pauses background media.' },
  { id: 'STATES-17', layer: 'States', tier: 'A', title: 'Multi-Tab Session Synchronization', description: 'Invalidates session when user logs out in an adjacent browser tab.' },
  { id: 'STATES-18', layer: 'States', tier: 'A', title: 'Session Expiration Warning Modal', description: 'Warns user 2 minutes prior to session expiration with extension button.' },
  { id: 'STATES-19', layer: 'States', tier: 'A', title: 'Background Token Refresh Heartbeat', description: 'Silently refreshes auth tokens before expiration to prevent dropouts.' },
  { id: 'STATES-20', layer: 'States', tier: 'A', title: 'LocalStorage Quota Exceeded Guard', description: 'Catches quota exceptions gracefully without halting app runtime.' },
  { id: 'STATES-21', layer: 'States', tier: 'A', title: 'SessionStorage Private Mode Fallback', description: 'Supports in-memory fallback when browser blocks cookie/storage access.' },
  { id: 'STATES-22', layer: 'States', tier: 'A', title: 'IndexedDB Connection Re-open Handler', description: 'Recovers client-side database connections after system wake.' },
  { id: 'STATES-23', layer: 'States', tier: 'A', title: 'WebSocket Reconnect Exponential Backoff', description: 'Prevents server DDOS by staggering reconnection attempts.' },
  { id: 'STATES-24', layer: 'States', tier: 'A', title: 'Background Tab Polling Throttler', description: 'Suspends non-critical polling loops when document.hidden is true.' },
  { id: 'STATES-25', layer: 'States', tier: 'A', title: 'Clipboard Permission Denied Notice', description: 'Provides manual copy fallback if browser rejects clipboard API.' },
  { id: 'STATES-26', layer: 'States', tier: 'A', title: 'Geolocation Permission Graceful Fallback', description: 'Allows manual zip/city entry when GPS location is denied.' },
  { id: 'STATES-27', layer: 'States', tier: 'A', title: 'Notification Permission Prompt Timing', description: 'Prompts for push alerts after user action rather than on initial page load.' },
  { id: 'STATES-28', layer: 'States', tier: 'A', title: 'Camera/Mic Permission Denied Explanation', description: 'Explains why media access is required and how to enable in browser settings.' },
  { id: 'STATES-29', layer: 'States', tier: 'A', title: 'File Upload Drag & Drop Hover State', description: 'Highlights drop zone border with blue/green glow during active drag.' },
  { id: 'STATES-30', layer: 'States', tier: 'A', title: 'File Upload File-Size Limit Warning', description: 'Warns user immediately before uploading files that exceed MB limit.' },
  { id: 'STATES-31', layer: 'States', tier: 'A', title: 'File Upload Format MIME Verification', description: 'Rejects unsupported file formats with clear permissible extension list.' },
  { id: 'STATES-32', layer: 'States', tier: 'A', title: 'Async Data Loading Skeleton Shimmer', description: 'Displays pulse/shimmer skeletons preserving layout dimensions.' },
  { id: 'STATES-33', layer: 'States', tier: 'A', title: 'Infinite Scroll Loading Spinner Sentinel', description: 'Displays subtle bottom spinner during pagination fetch.' },
  { id: 'STATES-34', layer: 'States', tier: 'A', title: 'Filter Tag "Clear All" Reset Control', description: 'Enables 1-click removal of all active multi-filter badges.' },
  { id: 'STATES-35', layer: 'States', tier: 'A', title: 'Multi-Select Counter Indicator', description: 'Displays "3 items selected" badge inside multi-select dropdowns.' },
  { id: 'STATES-36', layer: 'States', tier: 'A', title: 'Accordion Open/Close State Memory', description: 'Smoothly animates accordion collapse without jumping page scroll.' },
  { id: 'STATES-37', layer: 'States', tier: 'A', title: 'Tab Panel Active State Selection', description: 'Marks current tab with aria-selected="true" and high-visibility border.' },
  { id: 'STATES-38', layer: 'States', tier: 'A', title: 'Dropdown Outside-Click Dismissal', description: 'Closes open menus when clicking anywhere outside container.' },
  { id: 'STATES-39', layer: 'States', tier: 'A', title: 'Hover Dropdown Intent Delay', description: 'Prevents dropdown collapse if pointer briefly leaves menu boundary.' },
  { id: 'STATES-40', layer: 'States', tier: 'A', title: 'Mobile Pull-to-Refresh State Indication', description: 'Displays progress spinner when user drags down on mobile view.' },

  // --- POLISH & MOTION (40 Checks) ---
  { id: 'POLISH-01', layer: 'Polish', tier: 'A', title: 'Prefers-Reduced-Motion Media Query Support', description: 'Suppresses motion and transforms when reduced-motion is requested in OS.' },
  { id: 'POLISH-02', layer: 'Polish', tier: 'A', title: 'Animation Duration Threshold (<=300ms)', description: 'Prevents sluggish, overlong UI animations that delay user interaction.' },
  { id: 'POLISH-03', layer: 'Polish', tier: 'A', title: 'GPU Composited Properties (Transform & Opacity)', description: 'Restricts animations to transform and opacity to maintain 60fps rendering.' },
  { id: 'POLISH-04', layer: 'Polish', tier: 'A', title: 'Scroll Jank & Frame Drop Elimination', description: 'Avoids heavy JavaScript scroll listeners without passive event flags.' },
  { id: 'POLISH-05', layer: 'Polish', tier: 'A', title: 'Smooth Anchor Scroll Behavior', description: 'Enables scroll-behavior: smooth on internal document fragment links.' },
  { id: 'POLISH-06', layer: 'Polish', tier: 'A', title: 'Custom Scrollbar Design Integration', description: 'Styles scrollbars to blend harmoniously with dark/light container canvas.' },
  { id: 'POLISH-07', layer: 'Polish', tier: 'A', title: 'Text Selection (::selection) Color Contrast', description: 'Applies branded high-contrast highlight background when highlighting text.' },
  { id: 'POLISH-08', layer: 'Polish', tier: 'A', title: 'Custom Focus Ring Geometry', description: 'Renders clean, rounded focus outlines matching element border radius.' },
  { id: 'POLISH-09', layer: 'Polish', tier: 'A', title: 'Micro-Interaction Spring Physics Easing', description: 'Uses cubic-bezier or spring easing rather than robotic linear timing.' },
  { id: 'POLISH-10', layer: 'Polish', tier: 'A', title: 'Card Hover Subtle Elevation Lift (-translate-y-1)', description: 'Provides subtle physical tactile feedback on hovering interactive cards.' },
  { id: 'POLISH-11', layer: 'Polish', tier: 'A', title: 'Button Active Pressed Scale (active:scale-98)', description: 'Applies momentary physical compression feedback on mouse down / tap.' },
  { id: 'POLISH-12', layer: 'Polish', tier: 'A', title: 'Action Icon Hover Micro-Rotation', description: 'Adds playful 3-5 degree rotation to iconography upon pointer hover.' },
  { id: 'POLISH-13', layer: 'Polish', tier: 'A', title: 'Card Border Gradient Highlight Glow', description: 'Renders subtle border shimmer on high-priority feature cards.' },
  { id: 'POLISH-14', layer: 'Polish', tier: 'A', title: 'Skeleton Shimmer Speed & Direction', description: 'Synchronizes loading shimmer gradients horizontally across cards.' },
  { id: 'POLISH-15', layer: 'Polish', tier: 'A', title: 'Toast Notification Slide-In Physics', description: 'Slides alerts in from screen corner with smooth dampening.' },
  { id: 'POLISH-16', layer: 'Polish', tier: 'A', title: 'Modal Pop-In Scale Spring Transition', description: 'Scales modal dialogs from 95% to 100% with gentle deceleration.' },
  { id: 'POLISH-17', layer: 'Polish', tier: 'A', title: 'Dropdown Menu Fade-In Ease-Out', description: 'Transitions dropdown menus with 100ms fade and 4px vertical slide.' },
  { id: 'POLISH-18', layer: 'Polish', tier: 'A', title: 'Mobile Navigation Drawer Slide-Out', description: 'Slides sidebar menu out from screen edge with backdrop blur.' },
  { id: 'POLISH-19', layer: 'Polish', tier: 'A', title: 'Page Navigation Soft Crossfade', description: 'Eliminates harsh white flash between route changes in Next.js.' },
  { id: 'POLISH-20', layer: 'Polish', tier: 'A', title: 'Progress Bar Smooth Easing Curve', description: 'Advances progress meters smoothly without discrete jumping.' },
  { id: 'POLISH-21', layer: 'Polish', tier: 'A', title: 'Button Ripple Radial Effect Cleanliness', description: 'Fades material ripple rings gracefully without leaving residual borders.' },
  { id: 'POLISH-22', layer: 'Polish', tier: 'A', title: 'Live Status Ping Badge Calibrated Opacity', description: 'Calibrates pulsing live indicator dots so they don’t distract reading.' },
  { id: 'POLISH-23', layer: 'Polish', tier: 'A', title: 'Typing Indicator Bouncing Dots Rhythm', description: 'Staggers 3 bouncing dots smoothly for conversational chat UIs.' },
  { id: 'POLISH-24', layer: 'Polish', tier: 'A', title: 'Metric Counter Number Ticker Animation', description: 'Animates stat counters rolling up to target value on first scroll view.' },
  { id: 'POLISH-25', layer: 'Polish', tier: 'A', title: 'Audio Feedback Volume & Mute Toggle', description: 'Provides master mute toggle if application includes audio clicks.' },
  { id: 'POLISH-26', layer: 'Polish', tier: 'A', title: 'Mobile Haptic Feedback Integration', description: 'Triggers subtle navigator.vibrate() on confirmation checkboxes.' },
  { id: 'POLISH-27', layer: 'Polish', tier: 'A', title: 'Dynamic Favicon Unread Notification Dot', description: 'Badges browser tab favicon with red indicator for unread alerts.' },
  { id: 'POLISH-28', layer: 'Polish', tier: 'A', title: 'Theme Toggle CSS Transition Dissolve', description: 'Smoothly blends dark/light mode background colors over 250ms.' },
  { id: 'POLISH-29', layer: 'Polish', tier: 'A', title: 'Gradient Mesh GPU Hardware Acceleration', description: 'Forces will-change: transform on animated background meshes.' },
  { id: 'POLISH-30', layer: 'Polish', tier: 'A', title: 'SVG Morph Path Transition Fluidity', description: 'Morphs hamburger menu icon to "X" close icon smoothly.' },
  { id: 'POLISH-31', layer: 'Polish', tier: 'A', title: 'Consistent Pointer Cursor Application', description: 'Applies cursor: pointer strictly to interactive controls.' },
  { id: 'POLISH-32', layer: 'Polish', tier: 'A', title: 'Interactive Element Hover Feedback', description: 'Ensures every clickable card or link indicates hover response.' },
  { id: 'POLISH-33', layer: 'Polish', tier: 'A', title: 'Mobile Tap Highlight Optimization', description: 'Sets -webkit-tap-highlight-color to transparent or custom tint.' },
  { id: 'POLISH-34', layer: 'Polish', tier: 'A', title: 'Overscroll Behavior Bounce Containment', description: 'Sets overscroll-behavior: contain to prevent parent page bounce.' },
  { id: 'POLISH-35', layer: 'Polish', tier: 'A', title: 'iOS Momentum Scrolling Enabler', description: 'Enforces -webkit-overflow-scrolling: touch on iOS scroll areas.' },
  { id: 'POLISH-36', layer: 'Polish', tier: 'A', title: 'Active Navigation Link Indicator', description: 'Highlights current route anchor in navbar with pill or underline.' },
  { id: 'POLISH-37', layer: 'Polish', tier: 'A', title: 'Sticky Navbar Blur & Border Transition', description: 'Deepens background blur and adds bottom border only when scrolled.' },
  { id: 'POLISH-38', layer: 'Polish', tier: 'A', title: 'Contrast Legibility on Glass Surfaces', description: 'Guarantees text remains legible over transparent frosted glass.' },
  { id: 'POLISH-39', layer: 'Polish', tier: 'A', title: 'Footer Brand Symmetry & Alignment', description: 'Aligns footer copyright, social links, and status badges cleanly.' },
  { id: 'POLISH-40', layer: 'Polish', tier: 'A', title: 'Retina & High-DPI Sharpness (2x / 3x)', description: 'Serves crisp @2x and @3x graphics on modern mobile screens.' },
];
